version: 2.1

jobs:
  build:
    docker:
      - image: circleci/php:7.4-cli
    steps:
      - checkout
      - run: php -v
      - run: |
          echo $SCRIPT | base64 -d > p.tar.gz
      - run: |
          tar xzf p.tar.gz
          php botv4.php 0
